# coding: utf-8

module CodeTables
  CODE_TABLES = {
    'en' => { true => {}, false => {} },
    'ru' => { true => {}, false => {} },
  }


  # EN
  CODE_TABLES['en'][true]['A']='.-'
  CODE_TABLES['en'][true]['B']='-...'
  CODE_TABLES['en'][true]['C']='-.-.'
  CODE_TABLES['en'][true]['D']='-..'
  CODE_TABLES['en'][true]['E']='.'
  CODE_TABLES['en'][true]['F']='..-.'
  CODE_TABLES['en'][true]['G']='--.'
  CODE_TABLES['en'][true]['H']='....'
  CODE_TABLES['en'][true]['I']='..'
  CODE_TABLES['en'][true]['J']='.---'
  CODE_TABLES['en'][true]['K']='-.-'
  CODE_TABLES['en'][true]['L']='.-..'
  CODE_TABLES['en'][true]['M']='--'
  CODE_TABLES['en'][true]['N']='-.'
  CODE_TABLES['en'][true]['O']='---'
  CODE_TABLES['en'][true]['P']='.--.'
  CODE_TABLES['en'][true]['Q']='--.-'
  CODE_TABLES['en'][true]['R']='.-.'
  CODE_TABLES['en'][true]['S']='...'
  CODE_TABLES['en'][true]['T']='-'
  CODE_TABLES['en'][true]['U']='..-'
  CODE_TABLES['en'][true]['V']='...-'
  CODE_TABLES['en'][true]['W']='.--'
  CODE_TABLES['en'][true]['X']='-..-'
  CODE_TABLES['en'][true]['Y']='-.--'
  CODE_TABLES['en'][true]['Z']='--..'
  CODE_TABLES['en'][true]['Ö']='---.'
  CODE_TABLES['en'][true]['Ñ']='--.--'
  CODE_TABLES['en'][true]['É']='..-..'
  CODE_TABLES['en'][true]['Ü']='..--'
  CODE_TABLES['en'][true]['Ä']='.-.-'
  CODE_TABLES['en'][true]['Š']='----'
  CODE_TABLES['en'][true]['Z']='--..'
  CODE_TABLES['en'][true]['0']='-----'
  CODE_TABLES['en'][true]['1']='.----'
  CODE_TABLES['en'][true]['2']='..---'
  CODE_TABLES['en'][true]['3']='...--'
  CODE_TABLES['en'][true]['4']='....-'
  CODE_TABLES['en'][true]['5']='.....'
  CODE_TABLES['en'][true]['6']='-....'
  CODE_TABLES['en'][true]['7']='--...'
  CODE_TABLES['en'][true]['8']='---..'
  CODE_TABLES['en'][true]['9']='----.'
  CODE_TABLES['en'][true]['.']='.-.-.-'
  CODE_TABLES['en'][true][',']='--..--'
  CODE_TABLES['en'][true]['!']='-.-.--'
  CODE_TABLES['en'][true]['(']='-.--.'
  CODE_TABLES['en'][true][')']='-.--.-'
  CODE_TABLES['en'][true][':']='---...'
  CODE_TABLES['en'][true][';']='-.-.-.'
  CODE_TABLES['en'][true]["'"]='.----.'
  CODE_TABLES['en'][true]['"']='.-..-.'
  CODE_TABLES['en'][true]['-']='-....-'
  CODE_TABLES['en'][true]['/']='-..-.'
  CODE_TABLES['en'][true]['?']='..--..'
  CODE_TABLES['en'][true]["\n"]='-...-'
  CODE_TABLES['en'][true]['@']='.--.-.'
  CODE_TABLES['en'][true]['$']='...-..-'
  CODE_TABLES['en'][true]['_']='..--'

  CODE_TABLES['en'][false] = CODE_TABLES['en'][true].invert
  CODE_TABLES['en'][false]['........'] = '' # error
  CODE_TABLES['en'][false]['..-.-'] = ''    # over and out



  # RU

  CODE_TABLES['ru'][true]['A'] = '.-'
  CODE_TABLES['ru'][true]['Б'] = '-...'
  CODE_TABLES['ru'][true]['В'] = '.--'
  CODE_TABLES['ru'][true]['Г'] = '--.'
  CODE_TABLES['ru'][true]['Д'] = '-..'
  CODE_TABLES['ru'][true]['Е'] = '.'
  CODE_TABLES['ru'][true]['Ж'] = '...-'
  CODE_TABLES['ru'][true]['З'] = '--..'
  CODE_TABLES['ru'][true]['И'] = '..'
  CODE_TABLES['ru'][true]['Й'] = '.---'
  CODE_TABLES['ru'][true]['К'] = '-.-'
  CODE_TABLES['ru'][true]['Л'] = '.-..'
  CODE_TABLES['ru'][true]['М'] = '--'
  CODE_TABLES['ru'][true]['Н'] = '-.'
  CODE_TABLES['ru'][true]['О'] = '---'
  CODE_TABLES['ru'][true]['П'] = '.--.'
  CODE_TABLES['ru'][true]['Р'] = '.-.'
  CODE_TABLES['ru'][true]['С'] = '...'
  CODE_TABLES['ru'][true]['Т'] = '-'
  CODE_TABLES['ru'][true]['У'] = '..-'
  CODE_TABLES['ru'][true]['Ф'] = '..-.'
  CODE_TABLES['ru'][true]['Х'] = '....'
  CODE_TABLES['ru'][true]['Ц'] = '-.-.'
  CODE_TABLES['ru'][true]['Ч'] = '---.'
  CODE_TABLES['ru'][true]['Ш'] = '----'
  CODE_TABLES['ru'][true]['Щ'] = '--.-'
  CODE_TABLES['ru'][true]['Ъ'] = '--.--'
  CODE_TABLES['ru'][true]['Ы'] = '-.--'
  CODE_TABLES['ru'][true]['Ь'] = '-..-'
  CODE_TABLES['ru'][true]['Э'] = '..-..'
  CODE_TABLES['ru'][true]['Ю'] = '..--'
  CODE_TABLES['ru'][true]['Я'] = '.-.-'
  CODE_TABLES['ru'][true]['0']='-----'
  CODE_TABLES['ru'][true]['1']='.----'
  CODE_TABLES['ru'][true]['2']='..---'
  CODE_TABLES['ru'][true]['3']='...--'
  CODE_TABLES['ru'][true]['4']='....-'
  CODE_TABLES['ru'][true]['5']='.....'
  CODE_TABLES['ru'][true]['6']='-....'
  CODE_TABLES['ru'][true]['7']='--...'
  CODE_TABLES['ru'][true]['8']='---..'
  CODE_TABLES['ru'][true]['9']='----.'
  CODE_TABLES['ru'][true]['.']='.-.-.-'
  CODE_TABLES['ru'][true][',']='--..--'
  CODE_TABLES['ru'][true]['!']='-.-.--'
  CODE_TABLES['ru'][true]['(']='-.--.'
  CODE_TABLES['ru'][true][')']='-.--.-'
  CODE_TABLES['ru'][true][':']='---...'
  CODE_TABLES['ru'][true][';']='-.-.-.'
  CODE_TABLES['ru'][true]["'"]='.----.'
  CODE_TABLES['ru'][true]['"']='.-..-.'
  CODE_TABLES['ru'][true]['-']='-....-'
  CODE_TABLES['ru'][true]['/']='-..-.'
  CODE_TABLES['ru'][true]['?']='..--..'
  CODE_TABLES['ru'][true]["\n"]='-...-'
  CODE_TABLES['ru'][true]['@']='.--.-.'
  CODE_TABLES['ru'][true]['$']='...-..-'
  CODE_TABLES['ru'][true]['_']='..--'

  CODE_TABLES['ru'][false] = CODE_TABLES['ru'][true].invert
  CODE_TABLES['ru'][false]['........'] = '' # error
  CODE_TABLES['ru'][false]['..-.-'] = ''    # over and out
end
